routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('admin/login/', function () {
    $role = App\Role::where(['slug'=>'agent'])->first();
    $user_id = DB::table('role_user')->where('role_id',$role->id)->value('user_id');
    $phone = App\User::where(['id'=>$user_id])->value('phone');
    return view('admin.login',compact('phone'));
})->name('user.login');
Route::get('admin/register/', function () {
    return view('admin.register');
});
Route::get('user/contact',function(){
    return view('contact.create');
});

    Route::resource('contacts','ContactController');

Route::post('admin/login','Admin\AdminController@login')->name('admin.login');
Route::post('admin/register','Admin\AdminController@register')->name('admin.register');
Route::get('admin/logout','Admin\AdminController@logout')->name('admin.logout'); 
Route::get('/stations/select', 'Admin\StationController@select')->name('stations.select');

Route::middleware('admin')->prefix('admin')->name('admin.')->namespace('Admin')->group(function()
{
    Route::get('index/', 'AdminController@index')->name('admin.index');
    Route::get('/user/role/{id}','UserController@createRole')->name('users.role');
    Route::get('/user/role/attach/{user}/{role}','UserController@storeRole')->name('users.role_attach');
    Route::get('/user/role/detach/{user}/{role}','UserController@detachRole')->name('users.role_detach');

    Route::get('orders/my_orders/index', 'OrderController@myOrdersIndex')->name('orders.my_orders.index');
    Route::post('orders/my_orders/accept', 'OrderController@myOrdersAccept')->name('orders.my_orders.accept');
    Route::post('orders/my_orders/confirm', 'OrderController@myOrdersConfirm')->name('orders.my_orders.confirm');
    Route::post('orders/my_orders/delete', 'OrderController@myOrdersDelete')->name('orders.my_orders.delete');
    Route::post('orders/my_orders/wait', 'OrderController@myOrdersWait')->name('orders.my_orders.wait');
    Route::post('orders/my_orders/ready', 'OrderController@myOrdersReady')->name('orders.my_orders.ready');
    Route::get('orders/canceleds/index', 'OrderController@canceleds')->name('orders.canceleds.index');
    Route::get('orders/closed/index', 'OrderController@closed')->name('orders.closed.index');

    Route::post('orders/complete','OrderController@orderComplete')->name('orders.complete');
    Route::get('orders/order_from_station/{id?}', 'OrderController@orderFromStation');
    Route::get('orders/order_train/{id?}', 'OrderController@orderTrain');
    Route::get('orders/order_wagon/{id?}', 'OrderController@orderWagon');
    Route::get('orders/order_container/{id?}', 'OrderController@orderContainer');
    Route::get('/orders/orderPrice/{id?}','OrderController@orderPrice')->name('orderPrice');
    Route::get('/products/productSelect/','ProductController@productSelect')->name('productSelect');

    Route::get('/companies/companySelect/','CompanyController@companySelect')->name('companySelect');
    Route::get('/products/company_product/{id?}','ProductController@companyProduct')->name('products.company_product');

    Route::get('/profil/account','UserController@account')->name('profil.account');
    Route::get('stores','StoreController@index')->name('stores.index');
    Route::post('stores/add','StoreController@add')->name('stores.add');
    Route::post('stores/getOut','StoreController@getOut')->name('stores.getOut');

    Route::post('/users/user_payment','TransactionController@user_payment')->name('transactions.user_payment');

    Route::post('/profil/user_check','TransactionController@user_check')->name('transactions.user_check');

    Route::post('banks/store','BankController@store')->name('banks.store');
    Route::post('banks/create/store','BankController@create_store')->name('banks.create.store');
    Route::post('banks/user_check','BankController@user_check')->name('banks.user_check');

    Route::resource('users', 'UserController');
    Route::resource('categories', 'CategoryController' );
    Route::resource('products', 'ProductController' );
    Route::resource('trains', 'TrainController' );
    Route::resource('countries', 'CountryController' );
    Route::resource('wagons', 'WagonController' );
    Route::resource('containers', 'ContainerController' );
    Route::resource('stations', 'StationController' );
    Route::resource('directions', 'DirectionController' );
    Route::resource('orders', 'OrderController');
    Route::resource('permissions', 'PermissionController');
    Route::resource('roles', 'RoleController');
    Route::resource('shippings','ShippingController');
    Route::resource('status','StatusController');
    Route::resource('companies','CompanyController');
    Route::resource('transactions','TransactionController');
    Route::resource('consumptions','ConsumptionController');
   


});

app/Station.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Station extends Model
{
    
    protected $fillable = [
        'name',
        'country_id'
    ];
    public function country(){

        return $this->belongsTo('App\Country');
    }
    public function directions(){

        return $this->belongsToMany('App\Direction');
    }
}

app/Http/Controllers/Admin/StationController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Station;
use Response;

class StationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $stations = Station::latest()->get();
        return view('admin.stations.index', compact('stations'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
        return view('admin.stations.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name' => 'required',
            'country_id' => 'required',
        ]);
        Station::create([
            'name' => $request['name'],
            'country_id' => $request['country_id'],
        ]);
        return redirect()->route('admin.stations.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($station)
    {
      return view('admin.stations.edit', compact('station'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $station)
    {
        $this->validate($request,[
            'name' => 'required',
            'country_id' => 'required',
        ]);
        Station::where(['id' =>$station->id])->update([
            'name' => $request['name'],
            'country_id' => $request['country_id'],
        ]);
        return redirect()->route('admin.stations.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($station)
    {
        $station->delete();
        return redirect()->route('admin.stations.index');
    }
    public function select(){
       
       $stations = Station::get();
        return Response::json($stations);
    }
}

resources/views/admin/stations/create.blade.php
@extends('admin.layouts.main')

@section('style')
    <link rel="stylesheet" href="{{ asset('admin/css/lib/chosen/chosen.min.css') }}">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>
    <style>
        .chosen-container{
            margin-left:15px;
            width:83% !important;
        }
    </style>
   
@endsection
@section('content')
<div id="right-panel" class="right-panel">
        
  @include('admin.includes.header')
    <div class="breadcrumbs">
        <div class="breadcrumbs-inner">
            <div class="row m-0">
                <div class="col-sm-5">
                    <div class="page-header float-left">
                        <div class="page-title">
                            <ol class="breadcrumb text-right">
                                <li><strong><a href="{{route('admin.stations.index')}}">Cтанций</a></strong></li>
                                <li class="">Добавить </li>
                            </ol>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
    <div class="content">
        <div class="animated fadeIn">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <strong>Форма элементов</strong> 
                        </div>
                        <div class="card-body">
                            <div class="card-body card-block">
                                <form action="{{ route('admin.stations.store')}}" method="post" enctype="multipart/form-data" class="form-horizontal">
                                    @csrf
                                    <div class="row">
                                        <div class="col-md-7">
                                            <div class="row form-group">
                                                <div class="col-12 col-sm-9">
                                                    <label for="name" class=" form-control-label">Имя</label>
                                                </div>
                                                <div class="col-12 col-sm-9">
                                                    <input type="text" id="name" name="name" placeholder="Имя" class="form-control">
                                                    @if($errors->has('name'))
                                                        <span style="font-size: 10px; color: red; float: left">{{ $errors->first('name') }}</span>
                                                    @endif
                                                </div>
                                            </div>
                                        </div>
                                         
                                    </div>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="row form-group">
                                                <div class="col-12 col-sm-9">
                                                    <label for="country_id" class=" form-control-label">Cтраны</label>
                                                </div>
                                                <select data-placeholder="" class="standardSelect" name ="country_id"tabindex="1">
                                                        <option value="">...</option>
                                                        @foreach(App\Country::latest()->get() as $country)
                                                            <option value="{{ $country->id }}"> {{ $country->name }}</option>
                                                        @endforeach
                                                 </select>
                                                    @if($errors->has('country_id'))
                                                        <span style="font-size: 10px; color: red; float: left;margin-left:15px;">{{ $errors->first('country_id') }}</span>
                                                    @endif
                                            </div>
                                        </div>    
                                    </div>
                                    <br>
                                    <div class="row form-group">
                                        <div class="col-12 col-sm-9">
                                            <button type="submit" class="btn btn-primary">Сохранить</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>                     
                </div>
            </div>
            
        </div><!-- .animated -->
    </div><!-- .content -->

    <div class="clearfix"></div>

</div><!-- /#right-panel -->

@endsection
@section('script')
<script src="{{ asset('admin/js/lib/chosen/chosen.jquery.min.js')}}"></script>

<script>
    jQuery(document).ready(function() {
        jQuery(".standardSelect").chosen({
            disable_search_threshold: 10,
            no_results_text: "Oops, nothing found!",
            width: "100%"
        });
    });
</script>
@endsection

resources/views/admin/stations/edit.blade.php
@extends('admin.layouts.main')

@section('style')
    <link rel="stylesheet" href="{{ asset('admin/css/lib/chosen/chosen.min.css') }}">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>
    <style>
        .chosen-container{
            margin-left:15px;
            width:83% !important;
        }
    </style>
   
@endsection
@section('content')
<div id="right-panel" class="right-panel">
        
  @include('admin.includes.header')
    <div class="breadcrumbs">
        <div class="breadcrumbs-inner">
            <div class="row m-0">
                <div class="col-sm-5">
                    <div class="page-header float-left">
                        <div class="page-title">
                            <ol class="breadcrumb text-right">
                                <li><strong><a href="{{route('admin.stations.index')}}">Cтанций</a></strong></li>
                                <li class="">Обновить </li>
                            </ol>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
    <div class="content">
        <div class="animated fadeIn">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <strong>Форма элементов</strong> 
                        </div>
                        <div class="card-body">
                            <div class="card-body card-block">
                                <form action="{{ route('admin.stations.update',['station' => $station->id])}}" method="post" enctype="multipart/form-data" class="form-horizontal">
                                    @csrf
                                    @method('PUT')
                                    <div class="row">
                                        <div class="col-md-7">
                                            <div class="row form-group">
                                                <div class="col-12 col-sm-9">
                                                    <label for="name" class=" form-control-label">Имя</label>
                                                </div>
                                                <div class="col-12 col-sm-9">
                                                    <input type="text" id="name" name="name" placeholder="Имя" class="form-control" value ="{{$station->name}}">
                                                    @if($errors->has('name'))
                                                        <span style="font-size: 10px; color: red; float: left">{{ $errors->first('name') }}</span>
                                                    @endif
                                                </div>
                                            </div>
                                        </div>
                                         
                                    </div>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="row form-group">
                                                <div class="col-12 col-sm-9">
                                                    <label for="country_id" class=" form-control-label">Cтраны</label>
                                                </div>
                                                <select data-placeholder="" class="standardSelect" name ="country_id"tabindex="1">
                                                        <option value="">...</option>
                                                        @foreach(App\Country::latest()->get() as $country)
                                                            <option value="{{ $country->id }}" @if($station->country_id == $country->id) selected @endif> {{ $country->name }}</option>
                                                        @endforeach
                                                 </select>
                                                    @if($errors->has('country_id'))
                                                        <span style="font-size: 10px; color: red; float: left;margin-left:15px;">{{ $errors->first('country_id') }}</span>
                                                    @endif
                                            </div>
                                        </div>    
                                    </div>
                                    <br>
                                    <div class="row form-group">
                                        <div class="col-12 col-sm-9">
                                            <button type="submit" class="btn btn-primary">Сохранить</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>                     
                </div>
            </div>
            
        </div><!-- .animated -->
    </div><!-- .content -->

    <div class="clearfix"></div>

</div><!-- /#right-panel -->

@endsection
@section('script')
<script src="{{ asset('admin/js/lib/chosen/chosen.jquery.min.js')}}"></script>

<script>
    jQuery(document).ready(function() {
        jQuery(".standardSelect").chosen({
            disable_search_threshold: 10,
            no_results_text: "Oops, nothing found!",
            width: "100%"
        });
    });
</script>
@endsection

resources/views/admin/stations/index.blade.php
@extends('admin.layouts.main')

@section('style')
    <link rel="stylesheet" href="{{ asset('admin/css/lib/datatable/dataTables.bootstrap.min.css') }}">
    
@endsection
@section('content')
    <div id="right-panel" class="right-panel">
        @include('admin.includes.header')
        <div class="breadcrumbs">
            <div class="breadcrumbs-inner">
                 <div class="row m-0">    
                    <div class="col-sm-8">
                        <div class="page-header float-left">
                            <div class="page-title">
                            <ol class="breadcrumb text-right">
                                <li><strong><a href="#">Cтанций</a></strong></li>
                                <li class="">Таблица</li>
                            </ol>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="page-header float-right">
                            <div class="page-title">
                                <a href="{{ route('admin.stations.create') }}" class="btn btn-primary btn-square" style="float: left;margin-top:7px;"><i class="ti-plus"></i> Добавить  </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="content">
            <div class="animated fadeIn">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                <strong class="card-title">Таблица данных</strong>
                            </div>
                            <div class="card-body">
                            <table id="bootstrap-data-table" class="table table-striped table-bordered">
                                    <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>Имя</th>
                                            <th>Cтраны</th>
                                            <th>Настройка</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach($stations as $station)
                                        <tr>
                                            <td>{{$station->id}}</td>
                                            <td>{{$station->name}}</td>
                                            <td>
                                                @if($station->country)
                                                    {{$station->country->name}}
                                                    @else нет Cтраны
                                                @endif     
                                            </td>
                                            <td class="text-center">
                                                <a class="btn btn-primary btn-xs" href="{{route('admin.stations.edit',['station'=>$station->id])}}"><i class="fa fa-pencil"></i></a>
                                    
                                                <form action="{{route('admin.stations.destroy',['station'=>$station->id])}}" method="post" style="display:inline-block">
                                                    @csrf
                                                    @method('delete')
                                                    <button class="btn btn-danger btn-xs"  onclick="return confirm('Вы действительно хотите удалить его?')"  type="submit"><i class="fa fa-trash"></i></button>
                                                </form>	
											</td>
                                            
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>                             
                            </div>
                        </div>
                    </div>


                </div>
            </div><!-- .animated -->
        </div>
       
        <div class="clearfix"></div>

        <!-- @include('admin.includes.footer') -->
    </div>
@endsection
@section('script')
    <script src="{{ asset('admin/js/lib/data-table/datatables.min.js') }}"></script>
    <script src="{{ asset('admin/js/lib/data-table/dataTables.bootstrap.min.js') }}"></script>
    <script src="{{ asset('admin/js/lib/data-table/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('admin/js/lib/data-table/buttons.bootstrap.min.js') }}"></script>
    <script src="{{ asset('admin/js/lib/data-table/jszip.min.js') }}"></script>
    <script src="{{ asset('admin/js/lib/data-table/vfs_fonts.js') }}"></script>
    <script src="{{ asset('admin/js/lib/data-table/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('admin/js/lib/data-table/buttons.print.min.js') }}"></script>
    <script src="{{ asset('admin/js/lib/data-table/buttons.colVis.min.js') }}"></script>
    <script src="{{ asset('admin/js/init/datatables-init.js') }}"></script>
    <script type="text/javascript">
        $(document).ready(function() {
          $('#bootstrap-data-table-export').DataTable();
      } );
    </script>
    
@endsection